---
- name: Install curl, locales, apt-transport-https, gnome desktop
  apt:
    name:
      - curl
      - locales
      - apt-transport-https
      - sshpass
      - apparmor-utils
      - gnome
    state: present
    update_cache: yes

- name: Install NTP
  apt:
    package: ntp
    state: present
      tags: ntp
      sudo: true

- name: Make sure NTP is started up
  service:
    name: ntp
    state: started
    enabled: yes
      tags: ntp
      sudo: true

# See https://www.pixelflush.com/blog/2013/03/29/fix-locale-setting-on-ubuntu-ec2-instances/
- name: Configure Locale as en_US.UTF-8
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Add /etc/hosts entries in DevSecOps-Box
  include_tasks: hosts_entry.yml
