---
# See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199 and
# https://github.com/geerlingguy/ansible-role-java/issues/64
- name: Ensure 'man' directory exists.
  file:
    path: /usr/share/man/man1
    state: directory
    recurse: true
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_version == '10.4.0'

- name: Ensure Java is installed.
  apt:
    update_cache: yes
    # name: "{{ java_packages }}"
    name: 'default-jdk'
    state: present
